### ISSUE TITLE
Implement Schrodle

### ISSUE THREAD

**Issue by thoresonjd** [thoresonjd/schrodle#1]
# Premise

Schrodle is a game that is inspired by [Wordle](https://en.wikipedia.org/wiki/Wordle) and the [Schrödinger's Cat](https://en.wikipedia.org/wiki/Schr%C3%B6dinger's_cat) thought experiment.

Similar to Wordle, a player is tasked with guessing the target word within the allotted number of attempts. After a guess, each letter is marked as present in or absent from the target word. If the letter is present within the target word, the letter can be either in the correct spot or the incorrect spot and is marked accordingly.

In addition to the target word, there is an "impostor" word. Whenever a guess is made, there is a 50% chance that the guess will be evaluated against the impostor rather than the target. In hard mode, each individual letter of the guess has a 50/50 chance of being evaluated against the corresponding letter in either the target or the impostor. If the same letter is guessed in the same spot for subsequent guesses, the letter may be reevaluated with respect to the other word. Thus, a letter can be marked as being simultaneously present and not present (or, if appearing in both the target and the impostor word, marked as simultaneously in the correct spot and not in the correct spot). Hence, the Schrödinger's cat thought experiment is, in essence, upheld.

# TODO

- [x] Implement high-level game management logic
- [x] Implement logic to select target and impostor words from dictionary
- [x] Implement logic to assess validity of a guess
- [x] Implement logic to mark individual letters according to presence in target or impostor word (50% chance)
- [x] Implement game board/grid/tile logic
- [x] Implement option to select between normal mode and hard mode
- [x] ~~Implement option to toggle between light mode and dark mode~~ Implement dark theme
- [x] Implement pop-up describing how to play the game
- [x] Implement exportable game end state (copy to clipboard) so players can share their results
- [ ] Allow for the game to maintain state
- [x] Beautify the UI
- [x] Write documentation (ensure project and code is well documented)
- [x] Deploy to web
