### ISSUE TITLE
Implement game board/grid/tile logic

### ISSUE THREAD

**Issue by thoresonjd** [thoresonjd/schrodle#5]
- [x] Develop a tile grid for Wordle-like UI (see #15 )
- [x] Implement logic to track state of each tile/letter and row/word in the grid (see #16 )
- [x] Implement keyboard listener to track when keys are typed (see #17 )
- [x] Upon typing a guess, match each letter to a tile, from left to right, in the next available row (requires keyboard input to be logged, ~~can also create an on-screen keyboard later on~~)
- [x] Create an on-screen keyboard (see #21 )
- [x] Trigger flipping animation on row advancement (see #25 )
- [x] Allow guess to be entered via the Enter key
- [x] If guess is invalid, display pop-up informing the player that the guess was invalid
- [x] If guess is valid, mark each letter according to presence in target or impostor letter (see #3 and #4 )
- [x] ~~If guess matches target word, no more guesses necessary~~ (we can delegate this to the game BLoC)
