### ISSUE TITLE
Implement high-level game management logic

### ISSUE THREAD

**Issue by thoresonjd** [thoresonjd/schrodle#9]
Game must manage:
- [x] Target and impostor word selection (see #2)
- [x] Guess validation (see #3)
- [x] Guess letter presence in target or impostor word (see #4)
- [x] Tile grid logic (see #5)
- [x] Exportable game results (see #8)
- [x] Implement hard mode option (see #32)

Perhaps we should find a way to manage high-level game state via BLoC?
